###    _____ _                    _    _____    ______ _                       _   ###
###   |_   _| |                  (_)  |_   _|   |  _  (_)                     | |  ###
###     | | | |__   ___ _ __ ___  _ ___ | | ___ | | | |_ ___  ___ ___  _ __ __| |  ###
###     | | | '_ \ / _ \ '_ ` _ \| / __|| |/ _ \| | | | / __|/ __/ _ \| '__/ _` |  ###
###     | | | | | |  __/ | | | | | \__ \| | (_) | |/ /| \__ \ (_| (_) | | | (_| |  ###
###     \_/ |_| |_|\___|_| |_| |_|_|___/\_/\___/|___/ |_|___/\___\___/|_|  \__,_|  ###

# Replace this with your webhook url
webhookUrl: copy your webhook url here

# What is the minimum score for a notification to be sent to the discord?
execution-threshold: 10.0
# What amount of new violations need to happen before another notification is sent?
repetition-threshold: 5.0
# What amount of time needs to pass before another notification is sent?
repetition-delay: 10.0

# Specify the embed color for each hack category
categoryColors:
  Boat Movement: "#875229"
  Flight / Y-Movement: "#3276bf"
  Speed: "#d6e600"
  Spoofed Packets: "#ff0000"
  Timer / Blink: "#d61ad6"
  Reach: "#6f1ad6"
  Elytra Flight: "#afaeb0"
  Illegal Packets: "#141414"

config-version: 2