name: ThemisToDiscord
version: '${project.version}'
main: xyz.earthcow.themistodiscord.ThemisToDiscord
api-version: '1.17'
depend:
  - Themis

commands:
  ttd:
    usage: §c/<command> <url | test | reload> [<url>]
    permission: themistodiscord.ttd

permissions:
  themistodiscord.ttd:
    description: Allows access to the /ttd command